### ISSUE TITLE
Failed to run ifcApi.Init() in nodejs

### ISSUE THREAD

**Issue by perstromswe** [IFCjs/web-ifc#268] opened 2022-11-10 15:03 UTC
I followed the example in /examples/nodejs/index.js

```
const WebIFC = require("./node_modules/web-ifc/web-ifc-api-node.js");

console.log("Hello web-ifc-node!");

const ifcapi = new WebIFC.IfcAPI();

export async function LoadFile(filename) {
  // load model data as a string
  const ifcData = fs.readFileSync(filename);

  await ifcapi.Init();

...
```

I'm getting error below. It's caused by the ifcApi.Init() function. Tried with different nodejs-versions (v18 & 19). Same result. Any suggestions?

```
TypeError: Failed to parse URL from /../node_modules/web-ifc/web-ifc.wasm
[ERROR] 15:46:49 RuntimeError: abort(TypeError: Failed to parse URL from /../node_modules/web-ifc/web-ifc.wasm). Build with -s ASSERTIONS=1 for more info.
/../node_modules/web-ifc/web-ifc-api-node.js:6689
              throw ex;
              ^

RuntimeError: abort(TypeError: Failed to parse URL from /../node_modules/web-ifc/web-ifc.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/../node_modules/web-ifc/web-ifc-api-node.js:7104:19)
    at process.emit (node:events:513:28)
    at process.emit (/../node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by QuimMoya** [comment] 2022-11-15 11:43
Hello @perstromswe 

You followed an example, and then your test fails, but the example itself works? Just curiosity.

**Comment by perstromswe** [comment] 2022-11-15 13:19
Hello @QuimMoya 
I did try to clone the repo but had problem get it up and running. Problem with env variables with emscripten. 
I started a clean nodejs project. Installed web-ifc with npm. Result above.

**Comment by sjovanovic** [comment] 2022-11-15 15:44
I can confirm I get the same error. Not sure what's wrong, just trying to load the ifc file in node.

**Comment by sjovanovic** [comment] 2022-11-15 16:04
Just run the nodejs example as the first post says.
I just noted that the issue may be the node version, node 18 and 19 are giving the error, so I downgraded to node 17 and it works.

On node 17 I get `TypeError: ifcapi.GetLineIDsWithType is not a function` but that may just be the faulty example.

**Comment by perstromswe** [comment] 2022-11-15 18:48
@sjovanovic Ah. I tried with version 16. It's working. Thanks.

**Comment by aka-blackboots** [comment] 2023-01-17 07:32
::take

**Comment by agviegas** [comment] 2023-01-17 07:32
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is February 7, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment] 2023-01-17 07:33
::drop

**Comment by agviegas** [comment] 2023-01-17 07:33
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by beachtom** [comment] 2023-02-13 07:39
So - it now seems to be working on Node at least v18 - so I think his is now solved. Let me know if you are still having issues.

**Closed by beachtom** 2023-02-13 07:39 UTC
Labels: bounty, status: available
