### ISSUE TITLE
Rebar model doesn't open

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#203] opened 2022-07-28 08:21 UTC
https://github.com/IFCjs/web-ifc-viewer/issues/106

**Comment by agviegas** [comment] 2022-08-09 19:09
::take

**Comment by agviegas** [comment] 2022-08-09 19:12
::take

**Comment by agviegas** [comment] 2022-10-11 10:21
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is November 1, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment] 2022-10-11 10:21
::drop

**Comment by agviegas** [comment] 2022-10-11 10:21
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by beachtom** [comment] 2023-08-11 10:00
This was a duplicate of #464 and has been fixed

**Closed by beachtom** 2023-08-11 10:00 UTC
Labels: bug, bounty, status: available
