### ISSUE TITLE
Add a callback progress

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc#104] opened 2021-11-08 20:40 UTC
#### Description

Add a progress callback to the loading process. The final objective is to provide a constant feedback to a user who is loading a model with web-ifc-three.

A super nice feature from a UX perspective :-)

#### Origin
![image](https://user-images.githubusercontent.com/18169247/140814638-7d034e98-ddd0-44f2-a0db-23d4a4dff3c3.png)

**Comment by agviegas** [comment] 2022-05-15 23:57
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by aka-blackboots** [comment] 2022-05-16 18:49
I'll like to take this bounty. Please let me know the process.

**Comment by aka-blackboots** [comment] 2022-05-19 04:39
Does this issue need a [Progress Bar](https://www.w3schools.com/howto/howto_js_progressbar.asp) something like this with proper details? 
If yes please let me know @agviegas

**Comment by agviegas** [comment] 2022-05-21 16:11
@aka-blackboots no! You just need to:

1. Find out where the ifc elements geometry are generated
2. Allow the user to give a callback function to web-ifc. That callback function should look like this: `(progress, total) => void`
3. Call that callback function each time a new ifc item is generated, passing the index of the current item and the total

If you have any questions on the way, let me know!

**Comment by agviegas** [comment] 2022-06-17 17:58
This bounty is free again!

**Comment by makc** [comment] 2022-06-18 04:56
@agviegas unfortunately, your little 3-step plan will not work. As is, web-if-three's LoadAllGeometry function calls ifcAPI.StreamAllMeshes with a callback to receive each geometry data which is executed inside this very function - corresponding c++ code in web-ifc-api.cpp is
```cpp
    for (auto& type : types)
    {
        auto elements = loader->GetExpressIDsWithType(type);
        StreamMeshes(modelID, elements, callback);
    }
```

if you want js to be able to reflect the progress, you would need to change API to "stream" these expressIDs instead of meshes, and then request meshes one by one in small numbers.

**Comment by makc** [comment] 2022-06-18 05:07
(for some context, on my laptop 169MB tower file from another issue is loaded and parsed in 2 seconds, and then 10 seconds are spent in StreamAllMeshes - this whole time the script is blocking the browser)

**Comment by agviegas** [comment] 2022-06-22 15:43
@makc I see 🤔 And would it be possible to know in advance the number of meshes to be streamed? If there was an additional method to do that, at least the user would now how many iterations of the callback of StreamAllMeshes would be called. I would consider that a possible solution to this!

**Comment by makc** [comment] 2022-06-24 02:22
@agviegas I totally forgot about this, sorry. Please check the above #186 - this kind of follows our discord discussion. There are a coupe of points to note:
- loading time increases (since we now give a browser extra idle time to reflect the progress), in case of 169MB file this means 15 seconds instead of 10;
- we have to wait until the progress is 100% before closing the model (so the code that used to close it immediately is likely going to break).

**Comment by makc** [comment] 2022-06-24 02:25
just to make sure - those points actually apply to web-if-three, changes to web-ifc (1st 2 commits) are not breaking

**Comment by makc** [comment] 2022-06-24 15:43
so @agviegas - if you make another LoadAllGeometryAsync (with progress callback, and maybe returning a Promise) in web-ifc-three instead, and leave LoadAllGeometry as-is, then none of this will be breaking. what do you think?

**Comment by agviegas** [comment] 2022-06-27 11:59
Hey @makc I'm a bit concerned about the time increase. Wouldn't it be possible to do something like this?

![image](https://user-images.githubusercontent.com/56475338/175936088-112ca92f-5176-456a-b813-06f65ca4b5ee.png)

**Comment by agviegas** [comment] 2022-08-08 22:59
Hey @makc how is this going? Did you manage to solve it? Cheers!

**Comment by makc** [comment] 2022-08-12 23:47
sorry @agviegas I forgot. give me until monday

**Comment by agviegas** [comment] 2022-08-13 18:44
::take

**Comment by agviegas** [comment] 2022-08-13 18:44
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is September 3, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment] 2022-08-13 18:44
::drop

**Comment by agviegas** [comment] 2022-08-13 18:44
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment] 2022-08-13 18:45
@makc no worries! Can you please use the ::take command like I did? We have just automated the managing of bounties :)

**Comment by makc** [comment] 2022-08-13 18:45
::take

**Comment by agviegas** [comment] 2022-08-13 18:45
### 🟢🟢🟢

> ::take

Hi, @makc! Thanks for taking this bounty! The due date is September 3, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by makc** [comment] 2022-08-13 18:47
@agviegas,
> make sure that the last and only the last PR has a title that either starts with the bounty ID

what's bounty id?

**Comment by agviegas** [comment] 2022-09-04 00:00
### 🔴🔴🔴

Hi, @makc! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by beachtom** [comment] 2022-12-08 08:49
::take

**Comment by agviegas** [comment] 2022-12-08 08:49
### 🟢🟢🟢

> ::take

Hi, @beachtom! Thanks for taking this bounty! The due date is December 29, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment] 2022-12-30 00:00
### 🔴🔴🔴

Hi, @beachtom! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by makc** [comment] 2023-01-08 02:41
::take

**Comment by agviegas** [comment] 2023-01-08 02:41
### 🟢🟢🟢

> ::take

Hi, @makc! Thanks for taking this bounty! The due date is January 29, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment] 2023-01-12 15:08
::done

**Comment by agviegas** [comment] 2023-01-12 15:08
### 🟢🟢🟢

> ::done

Hi, @makc! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment] 2023-01-12 15:20
### 🔴🔴🔴

> ::expense::118348

Hi, @makc! We cannot find a new expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.

**Comment by agviegas** [comment] 2023-01-16 06:16
::expense::118348

**Closed** 2023-01-16 06:17 UTC
Labels: bounty, status: paid
