### ISSUE TITLE
Wall openings is not displayed

### ISSUE THREAD

**Issue by krosoftware** [IFCjs/web-ifc#196] opened 2022-07-14 05:09 UTC
Hello
IFC files does not display some wall openings, please check image. On some other viewer, it is displayed. 
IFC file: https://easyupload.io/iy1jfm
bad image: https://postimg.cc/LJFDTjmv
OK image: https://postimg.cc/SjwfScYq
Thank you for your help.

**Comment by QuimMoya** [comment] 2022-08-04 06:40
I think the hole is made, but for some unknown reason there is a thin layer blocking the hole
![image](https://user-images.githubusercontent.com/12625508/182780208-db274639-0d3f-4c17-ba2f-71fd0222169a.png)

**Comment by aka-blackboots** [comment] 2022-10-11 09:06
::take

**Comment by agviegas** [comment] 2022-10-11 09:06
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is November 1, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment] 2022-10-11 09:06
::drop

**Comment by agviegas** [comment] 2022-10-11 09:06
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by BSchafer01** [comment] 2022-10-18 19:38
The link for the model appears to have expired. Would you be able to attach the model again?

**Comment by aka-blackboots** [comment] 2022-10-22 10:51
@BSchafer01, connect with me on discord, and I will share a basic IFC file with you.

**Comment by Exathera** [comment] 2022-11-09 11:09
Hello,
I have the same problem with this file: https://easyupload.io/m1k0le.
Some Openings are displayed correctly, but others dont.
Hope this file can help.
Thank you

**Comment by sanvie** [comment] 2022-11-25 14:43
Hi,
I think I have the same problem with a "public" IFC file: AC20-FZK-Haus.ifc (so easily retrieved by anyone and pretty small one).
Some (most openings) are "closed" by a thin layer. When exporting "only" the IFCOPENINGELEMENT it see a strange thing: this thin layers is there.. so it is not a result of the boolean op... (it is in a way) but that in the first place the geometry to "remove" from the wall to create the hole contains that non manifold thin layer. 

The model should look like this:
![image](https://user-images.githubusercontent.com/3609428/204007565-4007098a-b789-4699-abfd-b87c1bb47fd3.png)

but the openings only are:
![image](https://user-images.githubusercontent.com/3609428/204007726-54cd9f5a-7526-48ca-8805-497124b83754.png)

there is a thin layer inside each ones... sometimes it gets removed and sometimes it stays there... don"t know it it helps...

**Comment by sanvie** [comment] 2022-11-27 08:32
Looking a bit closer into this issue... it looks like in the IFC file, the geometry used to create the hole is defined (most of the time) as 
#32472= IFCSHAPEREPRESENTATION(#118,'Body','SweptSolid',(#32455,#32471));
I guess this means 2 reps are used to define the shape. Both are extruded 
#32455= IFCEXTRUDEDAREASOLID(#32445,#32452,#32453,0.3);
(why a software would end up generating this... I don't know, specifically considering both "blocks" are same size and basically stand back to back).
I assume webIFC generates the 2 geometries and pool them together in a single geometry.
In turns, when boolean substract is called, it is called between a geometry and this 'pooled result' of two back to back geometry. 
The isInsideMesh function is then unable to provide the correct answer for those duplicated back to back triangles (moreover, answer is probably inconsistent depending on the ray direction)

**Comment by pbbr** [comment] 2022-12-16 09:21
We have the same issue on several models. @sanvie Do you have an idea how to proceed on this topic?

**Comment by QuimMoya** [comment] 2022-12-16 09:41
> 

We are working on this issue, this is related to the solids library we are using.

Sorry for the inconvenience.

**Comment by pbbr** [comment] 2022-12-16 09:53
Thanks for your feedback. Good to know that you are working on.

**Comment by pbbr** [comment] 2023-02-18 10:07
https://github.com/IFCjs/web-ifc/releases/tag/0.0.37 Great update, congrats and many thanks to the team! There's much better support for complex solids with this release.

What we saw is, that there is still an issue with openings. It seems that the parsing has changed for openings, but not in a way to solve the problem (see https://github.com/IFCjs/web-ifc/issues/196#issuecomment-1354482639). 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/79220314/219854547-9669d61d-c4cd-450a-b3d6-da5b91ddf397.png">

Do you have any plans to improve the parsing for openings?

**Comment by QuimMoya** [comment] 2023-02-20 05:45
@pbbr and @krosoftware 
The new solids engine solves many previous issues, but not all. As you may know, solids are one of the most complex areas in programming. This problem cannot be solved in one step, there are literally hundreds of edge cases.
With the new engine we can improve it over time because it does not rely on external libraries. It means that, in the coming months we will be solving specific solids issues one by one.
Your file is one of these cases, I’m going to add it to the list.

Thanks

**Comment by MagicalBloom** [comment] 2023-02-20 07:11
I have one example with broken walls as well and I'll probably come across more in the future. Should I add those in here or create a new issue for each one? @QuimMoya

**Comment by pbbr** [comment] 2023-02-20 07:48
@QuimMoya Thanks for your feedback. I understand the complexity and that not every problem can be solved right now. We have a lot of models were the openings are the main issue. Other complex solids have a lower priority in my opinion.

Attached the problematic ifc file. If you like to have more example please get back to me.

[Test Model Openings.zip](https://github.com/IFCjs/web-ifc/files/10781558/Test.Model.Openings.zip)

**Comment by QuimMoya** [comment] 2023-02-20 08:19
@MagicalBloom Add the files here, i will use them for testing.

Thanks

**Comment by MagicalBloom** [comment] 2023-02-20 10:18
https://www.dropbox.com/s/mci7l5mdjxwpvjb/walls.ifc

**Comment by QuimMoya** [comment] 2023-02-21 16:21
![image](https://user-images.githubusercontent.com/12625508/220401202-0151a133-bd84-42e9-a1c3-0db3953acd65.png)
Should be something like this?

**Comment by MagicalBloom** [comment] 2023-02-21 16:42
There seems to be something weird going on in the left corner, nut other than that it looks good. I should probably add reference images for any future models.

Here is one for this one:
![image](https://user-images.githubusercontent.com/7040679/220406324-a6c48cbc-063a-4255-bdf1-2f9ebcdb4417.png)

**Comment by pbbr** [comment] 2023-03-25 11:10
@QuimMoya With the latest changes our issues regarding openings (https://github.com/IFCjs/web-ifc/issues/196#issuecomment-1435586011) are now solved, thanks a lot!

**Closed** 2023-03-25 11:31 UTC
Labels: bug, bounty, status: available

**Comment by makc** [comment] 2023-04-17 11:18
@agviegas another bounty that is [still open](https://airtable.com/embed/shrD7oOspTUpElFX9/tblKwrKdBmdTG2L3I/viwu2a2cJLvEFTvA6/rec1jlGpzGltcpcAc?backgroundColor=orange&viewControls=on). I guess most of the bounties are outdated now?

**Comment by agviegas** [comment] 2023-04-17 13:44
@makc On it!
