### ISSUE TITLE
[Bug]: large ifc models fails

### ISSUE THREAD

**Issue by skemaikin** [IFCjs/web-ifc#419] opened 2023-06-19 12:52 UTC
### What happened?

Hi!
When I try to open large models (approximately 2Gb or larger ones) I receive an error. As far as I understand, the error occurs inside the wasm module. The small ifc models load well.
I have written a simple test node project to demonstrate the problem. It includes a sample large ifc model, so the project's size is ~460Mb.  The project was tested on Ubuntu 22.04, node versions: 15.14.0, 16.18.1, 18.16.0.

Project link: https://drive.google.com/file/d/1P0GiKXHa613mnk7w7KPlu4ipcNPfrJoF/view?usp=sharing

Installing command: npm install
Test command: node index.js
The **index.js** file contains `LoadFile('data/small.ifc')` instruction for small model. Change it by the `LoadFile('data/large.ifc')` to produce an error.

### Version

0.0.41

### Relevant log output

```shell
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (/home/test/web-ifc-test/node_modules/web-ifc/web-ifc-api-node.js:5273:19)
    at _abort (/home/test/web-ifc-test/node_modules/web-ifc/web-ifc-api-node.js:7008:11)
    at <anonymous>:wasm-function[49]:0x140e
    at <anonymous>:wasm-function[80]:0x6564
    at <anonymous>:wasm-function[382]:0x39bf0
    at <anonymous>:wasm-function[853]:0x8c804
    at <anonymous>:wasm-function[997]:0x9271e
    at Object.OpenModel (eval at new_ (/home/test/web-ifc-test/node_modules/web-ifc/web-ifc-api-node.js:1:1), <anonymous>:9:10)
    at IfcAPI2.OpenModel (/home/test/web-ifc-test/node_modules/web-ifc/web-ifc-api-node.js:63143:34)
    at LoadFile (/home/test/web-ifc-test/index.js:42:28)
```

**Comment by beachtom** [comment] 2023-06-29 19:39
Thanks for this - this is the biggest model we've had. It uncovered a few issues in the parser that I've now fixed. LEt us know how you get on!

**Closed by beachtom** 2023-06-29 19:39 UTC
Labels: bug

**Comment by skemaikin** [comment] 2023-06-29 19:58
> Thanks for this - this is the biggest model we've had. It uncovered a few issues in the parser that I've now fixed. LEt us know how you get on!

Can I check it on web-ifc-viewer repo?

**Comment by skemaikin** [comment] 2023-06-29 20:33
With the current build, the test application loads the large model well!

**Comment by arpu** [comment] 2023-06-30 13:25
hi @skemaikin  how do you load this model in the web?

**Comment by skemaikin** [comment] 2023-06-30 13:45
> hi @skemaikin how do you load this model in the web?

Unfortunately, I have not yet been able to load the large model via the web by changing the loader code in the web-ifc-viewer project. If someone manages to do this, I will be very grateful for the code.

**Comment by beachtom** [comment] 2023-06-30 14:59
I suspect the issue is with the file upload in the demo viewers
I think you will need to write some JS to download it from a URL - unzip it - and then pass it to web-ifc.

Happy to advise to see it working - let me know how you get on
