### ISSUE TITLE
IFC File without IFCSite

### ISSUE THREAD

**Issue by UUTek** [IFCjs/web-ifc#117] opened 2021-12-13 08:25 UTC
Autodesk Civil 3D generated IFC files (v. IFC 2x3, IFC4, IFC4x1) does not have IFCSite().  The render of this file is not correct on web-ifc viewer.

**Comment by tomvandig** [comment] 2022-01-28 20:43
Hi, do you have an example file>?

**Comment by myshuji** [comment] 2022-03-15 05:37
[ifcsite.zip](https://github.com/tomvandig/web-ifc/files/8250469/ifcsite.zip)

**Comment by Manriss** [comment] 2022-03-30 13:49
Same problem here.

**Comment by agviegas** [comment] 2022-05-15 23:54
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by Zegeri** [comment] 2022-05-30 06:07
> [ifcsite.zip](https://github.com/tomvandig/web-ifc/files/8250469/ifcsite.zip)

This example has an IFCSite step at #31947.

**Comment by QuimMoya** [comment] 2022-06-21 11:30
Hello, this model is not being represented because there is no "body" key in IFCSHAPEREPRESENTATION
if you modify the line 
#31935= IFCSHAPEREPRESENTATION(#98,'Facetation','SurfaceModel',(#31924));
to
#31935= IFCSHAPEREPRESENTATION(#98,'**Body**','SurfaceModel',(#31924));
... you obtain this geometry, associated to the object SITE
![image](https://user-images.githubusercontent.com/12625508/174789021-bbb4b62e-0190-43e8-89e9-85d04afbbfdf.png)

**Comment by agviegas** [comment] 2022-10-18 16:53
### 🟢🟢🟢

> ::take

Hi, @BSchafer01! Thanks for taking this bounty! The due date is November 8, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by BSchafer01** [comment] 2022-10-26 20:48
This issue should be resolved with pull request #237 that was merged earlier

**Comment by BSchafer01** [comment] 2022-11-01 16:14
::done

**Comment by agviegas** [comment] 2022-11-01 16:50
::done

**Comment by agviegas** [comment] 2022-11-01 16:50
### 🟢🟢🟢

> ::done

Hi, @BSchafer01! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by BSchafer01** [comment] 2022-11-02 15:43
::expense::104185

**Comment by agviegas** [comment] 2022-11-02 15:43
### 🔴🔴🔴

> ::expense::104185

Hi, @BSchafer01! We cannot find a new expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.

**Comment by BSchafer01** [comment] 2022-11-02 15:47
Hi @agviegas I've messed up the flow of the automation I believe. The expense has already been approved. I didn't use the "done" command until the expense was approved on Open Collective. Sorry about the confusion

**Comment by agviegas** [comment] 2022-11-02 21:34
No problem!

**Closed** 2023-02-04 08:39 UTC
Labels: bounty, status: done
