### ISSUE TITLE
Some exterior walls not visible in 3D view when exported in IFC 2x3 

### ISSUE THREAD

**Issue by salpbes** [IFCjs/web-ifc#451] opened 2023-07-20 11:08 UTC
### What happened?

It seems some of the walls are not visible when exported with the IFC 2x3 schema. Problematic exterior walls are visible if they are exported with IFC 4 schema. In some other IFC viewers even in IFC 2x3 schema problematic exterior walls are visible.

https://drive.google.com/drive/folders/1tyMV9n-b2D1Ta4hryzg6a8oW-K_kNYxr?usp=sharing

### Version

0.0.42

### What browsers are you seeing the problem on?

Chrome

### Anything else?

<img width="612" alt="All IFC Export Settings" src="https://github.com/IFCjs/web-ifc/assets/99840912/660a79ab-43ac-482d-ba5c-4c4afab4d5cc">

![IFCjs 2x3](https://github.com/IFCjs/web-ifc/assets/99840912/cdc05cae-87ca-430c-822c-e86bd87c5dc6)

![Solibri IFC 2x3](https://github.com/IFCjs/web-ifc/assets/99840912/07cdd6bd-fc33-4d88-8be1-450442711d08)

![ACCA](https://github.com/IFCjs/web-ifc/assets/99840912/c4ee0b83-c8fd-476e-921c-eae918d38824)

![REVIT](https://github.com/IFCjs/web-ifc/assets/99840912/6b4b9446-54bb-477b-8259-edae2c0c7c46)

https://drive.google.com/drive/folders/1tyMV9n-b2D1Ta4hryzg6a8oW-K_kNYxr?usp=sharing

**Comment by jespa007** [comment] 2023-07-20 11:17
Hi @salpbes  please check if the model is loaded correctly from the [web-ifc demo page](https://ifcjs.github.io/web-ifc/demo/). Its seems web-ifc-viewer doesn't has the last web-ifc version.

**Comment by salpbes** [comment] 2023-07-20 11:21
Hi @jespa007, thanks for the reply. I already tested it with @agviegas suggestion. Still have the same problem.

**Comment by arpu** [comment] 2023-07-20 11:34
Hi, can you share why you not simple use the  IFC 4 schema? looks like the filesize is smaller and it works?

**Comment by salpbes** [comment] 2023-07-20 12:11
Hi @arpu, some of our works are dependent on IFC 2x3 data. I really wish to work solely on IFC4 in the future. 🤞

**Comment by arpu** [comment] 2023-07-20 12:48
good to know there is some data, we can not use in IFC4 at this point?

**Comment by salpbes** [comment] 2023-07-24 12:09
Hi all, I wanted to provide an update regarding the issue with the exterior walls. I copied it to another location and did not encounter any problems. But I still have a problem with the exterior walls in the original location. I have attached screenshots for you to look over.

![IFC-01](https://github.com/IFCjs/web-ifc/assets/99840912/0945f136-22d6-40a4-a5b5-992ef9b5f15a)
![IFC-02](https://github.com/IFCjs/web-ifc/assets/99840912/21713acc-36f1-480d-b689-8d1d47e43c4a)

I assume the problem may be related to Parts inside the wall, especially the Air Barrier's transparent layer.

**Comment by QuimMoya** [comment] 2023-07-25 13:11
![image](https://github.com/IFCjs/web-ifc/assets/12625508/23069380-cdd8-42d8-89b6-802ae1a5da27)

The face of the wall is not missing, but normals are wrong. I opened the IFC2X3 with web-ifc-viewer and it worked correctly. Moreover if you look at the wall from inside the building, it is visible, so the problem seems to be related to normals.

**Comment by salpbes** [comment] 2023-07-25 14:09
Hi @QuimMoya,
Sorry I can't understand, so you opened the IFC2x3 version and can see the wall in web-ifc-viewer, am I right?
I still don't have it on my end.
![image](https://github.com/IFCjs/web-ifc/assets/99840912/c1b3a054-a3a6-49f1-b7a4-97a20ab10cb7)
![image](https://github.com/IFCjs/web-ifc/assets/99840912/e8e85ce5-a4f3-4f92-bdb4-0c15258bcd5c)

**Comment by QuimMoya** [comment] 2023-07-25 14:31
Maybe i miss something.... i will review that again.

**Comment by agviegas** [comment] 2023-07-26 20:29
@salpbes it is likely that web-ifc-viewer doesn't have the latest version of web-ifc, as we are now focusing our efforts into [this repository](https://github.com/ifcjs/components), which will substitute web-ifc-three and web-ifc-viewer very soon (including a full documentation with tutorials and examples). To check out the latest changes in web-ifc, you can try [this viewer](https://ifcjs.github.io/web-ifc/demo/).

**Comment by salpbes** [comment] 2023-07-27 07:54
Hello @agviegas, it's great to speak with you again,
as we spoke earlier on LinkedIn I already tried https://ifcjs.github.io/web-ifc/demo/.
Here is the screenshot again
![image](https://github.com/IFCjs/web-ifc/assets/99840912/666648ac-dd45-4982-89d2-32a1156015b2)

**Comment by jespa007** [comment] 2023-07-27 09:38
@salpbes I have tested the model *Snowdon Towers Sample Architectural_IFC2x3.ifc* and it loads without the issue in the [web-ifc-three demo page](https://ifcjs.github.io/web-ifc-three/example/). So I suspect is something is missing in the render configuration or in model 3d that is created in the demos pages web-ifc or web-ifc-viewer.

![image](https://github.com/IFCjs/web-ifc/assets/7852409/8eed8491-7a3b-4cb2-aa5a-8a27488d9aaf)

**Comment by salpbes** [comment] 2023-07-27 09:53
Hi @jespa007, https://ifcjs.github.io/web-ifc-three/example/  is the latest and updated website for the test, am I right?

If you look at my previous post,  
https://github.com/IFCjs/web-ifc/issues/451#issuecomment-1649919465
![image](https://github.com/IFCjs/web-ifc/assets/99840912/a06f39da-041f-4b53-9dfc-aedc83ec1605)

You can see that when the wall is separated from the building it is rendered %100. Something causes it to be rendered weird when it's connected to the building.

**Comment by jespa007** [comment] 2023-07-27 10:01
@salpes the demo page is web-ifc-three not  web-ifc.  

https://ifcjs.github.io/web-ifc-three/example/

**Comment by salpbes** [comment] 2023-07-27 10:37
Ok, @agviegas previously suggested using https://ifcjs.github.io/web-ifc/demo/ to me.
In summary, from what I understand, the identical IFC file(2x3) appears differently in various modules. Do you know what causes this?

- web-ifc - (file loads with issue)
![image](https://github.com/IFCjs/web-ifc/assets/99840912/2d42e251-d1b1-4cd2-a7b8-b2491710ff9d)

- web-ifc-three - (no issue)
![image](https://github.com/IFCjs/web-ifc/assets/99840912/5d7063dd-71ec-4287-9b28-5ea06d523191)

- web-ifc-viewer - (file loads with issue)
![image](https://github.com/IFCjs/web-ifc/assets/99840912/5288b151-1f01-4595-b2bd-bb3dbc32231a)

**Comment by jespa007** [comment] 2023-07-27 10:47
@salpbes as far I can see is an issue related how the model is loaded. Maybe the geometry on transparent layer (that you mentionend early) are ignored

**Comment by beachtom** [comment] 2023-07-27 11:36
https://ifcjs.github.io/web-ifc/demo/  is the one to go off. If it is not working there it means some regression has been introduced - I think some normals are getting flipped

**Comment by jespa007** [comment] 2023-07-27 14:17
> https://ifcjs.github.io/web-ifc/demo/ is the one to go off. If it is not working there it means some regression has been introduced - I think some normals are getting flipped

@beachtom, before do nothing I ask to @agviegas wether it can help in this issue because I'm using web-ifc-three with the latest web-ifc ( I compile manually in order to update) and in my case it works. I think is a issue of rendering configuration or how the model is loaded or maybe some material different added diffrerent from web-ifc o web-ifc-viewer.

**Comment by RyugaRyuzaki** [comment] 2023-07-27 16:33
> 

The reason why web-ifc-three is not experiencing an issue is that it is currently using version web-ifc@0.0.39, despite the latest version being web-ifc-three@0.0.125. You can try this in the command: list web-ifc, and you will see. Please attempt to access the following example: https://github.com/IFCjs/components/blob/main/examples/fragment-loader-ifc.html#L105. After that, sequentially change the versions of web-ifc to 0.0.40, 41, 42, and you will observe the error "this.wasmmodule.OpenModel is not a function."

**Comment by RyugaRyuzaki** [comment] 2023-07-27 16:36
> > https://ifcjs.github.io/web-ifc/demo/ is the one to go off. If it is not working there it means some regression has been introduced - I think some normals are getting flipped
> 
> @beachtom, before do nothing I ask to @agviegas wether it can help in this issue because I'm using web-ifc-three with the latest web-ifc ( I compile manually in order to update) and in my case it works (I don't see the issue). I think is a issue of rendering configuration or how the model is loaded or maybe some material different added diffrerent from web-ifc o web-ifc-viewer.

![image](https://github.com/IFCjs/web-ifc/assets/89787521/cd4cc24e-f263-4cdb-9ac8-ccbc21acba89)

**Comment by jespa007** [comment] 2023-07-28 08:29
> The reason why web-ifc-three is not experiencing an issue is that it is currently using version web-ifc@0.0.39

 I'm using web-ifc-three with the latest web-ifc ( I compile that manually in order to update), I mean I'm using web-ifc-three 0.0.125 with web-ifc downladed from github at 2023-07-19

**Comment by jespa007** [comment] 2023-08-01 08:10
Good new @salpbes . I've discovered the cause of not rendering the walls.  The problem is the web-viewer where the material of merged geometries only rendered front faces and not both.

I did the PR :-)

https://github.com/IFCjs/web-ifc/pull/457

**Comment by beachtom** [comment] 2023-08-01 08:12
Great spot! Thanks. Will approve PR as soon as pipelines run

**Closed by beachtom** 2023-08-01 08:12 UTC
Labels: bug

**Comment by salpbes** [comment] 2023-08-01 08:16
Thank you @jespa007 @beachtom @RyugaRyuzaki @arpu @QuimMoya @agviegas and everyone. Your work is truly impressive.
