### ISSUE TITLE
WriteLine only works for existing Lines

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#290] opened 2022-12-12 14:42 UTC
https://github.com/IFCjs/web-ifc-three/blob/f88394d0d32371631aa0e79fe768125966941353/web-ifc-three/src/IFC/web-workers/workers/WebIfcWorker.ts#L156

```
        const object = this.webIFC.GetLine(modelID, serializedObject.expressID);
        Object.keys(serializedObject).forEach(propName => {
            if(object[propName] !== undefined) {
                object[propName] = serializedObject[propName];
            }
        })
```

As one can see in the Code above, WriteLine only works for Existing Lines, this is due to the fact that everytime we write a Line we retrieve one with the given expressID, and in case of a non existing Line it returns the line with expressID `1` which is probably a line that is not going to reflect the structure we seek

**Comment by D4ve-R** [comment] 2023-01-31 12:10
::take

**Comment by agviegas** [comment] 2023-01-31 12:10
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is February 21, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by D4ve-R** [comment] 2023-01-31 12:10
should be fixed, with this pr #315. 
Realized to late this was a bounty. 
To write new lines, simply create a lineObject with expressID  < 0.
I haven't tested the behavior for non existent lines for `GetLine`. 
If true this could be a big issue because of unintentionally overwriting something. 
I can test that and create a separate issue, if it turns out to be one.

**Comment by D4ve-R** [comment] 2023-01-31 12:13
@agviegas, can be marked as done

**Closed** 2023-02-04 08:27 UTC
Labels: bounty, status: in progress

**Comment by agviegas** [comment] 2023-02-05 12:52
::done

**Comment by agviegas** [comment] 2023-02-05 12:52
### 🟢🟢🟢

> ::done

Hi, @D4ve-R! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by D4ve-R** [comment] 2023-02-05 13:37
::expense::122016

**Comment by agviegas** [comment] 2023-02-05 13:37
### 🟢🟢🟢

> ::expense::122016

Hi, @D4ve-R! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment] 2023-02-05 22:35
### 🟢🟢🟢

Hi, @D4ve-R! Your [expense](https://opencollective.com/ifcjs/expenses/122016) has been approved!

**Comment by agviegas** [comment] 2023-02-07 20:01
### 🎉🎉🎉

Hi, @D4ve-R! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
