### ISSUE TITLE
[Bug]: DERIVEDUNITEXPONENT is written as a REAL and not as INTEGER

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#534] opened 2023-12-18 21:09 UTC
### What happened?

Reading from and Writing a File which contains IFCDERIVEDUNITELEMENTS parses the Exponent Values as Real numbers and not as Integers (as seen below)
`
#280=IFCDERIVEDUNITELEMENT(#20,-2.);
#281=IFCSIUNIT(*,.MASSUNIT.,.NANO.,.GRAM.);
#282=IFCDERIVEDUNITELEMENT(#281,1.);
#283=IFCDERIVEDUNITELEMENT(#69,-1.);
#284=IFCDERIVEDUNITELEMENT(#34,-1.);
#285=IFCDERIVEDUNIT((#280,#282,#283,#284),.VAPORPERMEABILITYUNIT.,$);
`

Opening a File with IFCJs then interprets the real number as a string and thus making the Unit faulty

### Version

0.0.46

**Comment by beachtom** [comment] 2024-01-19 14:45
This is now fixed

**Closed by beachtom** 2024-01-19 14:45 UTC
Labels: bug

**Comment by fkleedorfer** [comment] 2024-02-02 13:58
While working around #522 (which is not a bug in IFC.js, but relevant for context), I noticed that the problem reported here also affects IFCDIMENSIONALEXPONENTS: when writing a file with such an object, the exponents are REAL values, not INTEGER:

Example:
```
#666=IFCDIMENSIONALEXPONENTS(1.,0.,0.,0.,0.,0.,0.);
#667=IFCMEASUREWITHUNIT(IFCLENGTHMEASURE(0.0254),#42);
#668=IFCCONVERSIONBASEDUNIT(#666,.LENGTHUNIT.,'Inch',#667);
#669=IFCPROPERTYSINGLEVALUE('Phase erstellt',$,IFCLENGTHMEASURE(13.7603),#668);
```

Haven't had a chance to check if it is fixed in then latest release, as well. Will file an issue if not.
