### ISSUE TITLE
Strange schema identifiers in src/

### ISSUE THREAD

**Issue by Moult** [IFCjs/web-ifc#255] opened 2022-10-28 00:51 UTC
In https://github.com/IFCjs/web-ifc/tree/main/src I see identifiers "2x4" and "4x2". Neither of these are official bSI schema identifiers. bSI identifies IFCs using two things 1) a version number (e.g. 2.3.0.1) and 2) a schema identifier (e.g. IFC2X3).

ifc2x4 does not exist, and neither does 4x2, is there a reason these files are named this way? Can you confirm that the actual dataset is being extracted from 2.3.0.1 and 4.0.2.1. respectively? (https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/)

Initially raised in #170

**Comment by beachtom** [comment] 2022-10-28 07:59
Hi Dion, thanks. I think this is also the cause of the issues here: https://github.com/IFCjs/web-ifc/issues/212

I am hoping to look at this in the next week or two

**Comment by Moult** [comment] 2022-10-28 08:31
Ah right. If so this is not just a cosmetic issue but a serious problem which should be fixed :)

**Comment by andy-wrks** [comment] 2022-11-28 13:59
There are some discussions about the handling of the schema version in the file header in the buildingSMART forums. Surprisingly, there's no clear outcome.
https://forums.buildingsmart.org/t/versioning-in-the-ifc-file/2796
https://forums.buildingsmart.org/t/file-schema-vs-schema-version/2750

From experience, it seems like all major software packages only indicate the main scheme version in the header. In practice, this means either "IFC2X3" or "IFC4".
We know with certeinty that these two aren't compatible with each other. However, my base assumption would be that when a new "official" IFC4 release happens, that it would be backwards compatible with the current official IFC 4.0.2.1 release. So in the future, when a file says "IFC4", it can be parsed using the most current IFC4 scheme and it will deliver the correct output, no matter which exact IFC4 scheme has been used to write the file. If not, it would be quite a failure in managing IFC releases and their implementations.
According to some sources on the web, IFC4.3 is expected to become an ISO standard in 2023 and thus a new "Official" release. It remains to be seen when the first implementations will be available and what the header will say. It's a bit concerning though, that buildingSMART has no clear information on this.

**Comment by beachtom** [comment] 2022-11-28 14:03
So I think my recent fix - largely resolves this issue. We now have IFC2X3 and IFC4 in web-ifc. I used these simply because they are what appear in the exp files. I guess we will just have to adapt to whatever BSI comes out with

**Comment by andy-wrks** [comment] 2022-11-28 14:24
I think support for the official versions should be good for now. In my opinion, all these discarded scheme versions and dumped release candidates have created a lot of confusion among users. I read quite some requirements documents for BIM models that mention entities that were never officially released in the data scheme, let alone implemented in software.

That said, I just did some digging and it looks like a potential official release of IFC4.3 will not be backwards compatible with IFC 4.0.2.1. The relevant information is given on this page from the IFC4.3 documentation:
http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/content/introduction.htm

According to buildingSMART, backwards compatibility is a "hard requirement", but not without exceptions. Interesting definition of a hard requirement... 🤯
![image](https://user-images.githubusercontent.com/111515188/204299320-1051b8b5-f24f-4f6c-9337-8a9d318516eb.png)

And the list of "exceptional" backwards incompatibilities between IFC4.3 and ISO 16739-1:2018 (which is IFC 4.0.2.1) is long:
![image](https://user-images.githubusercontent.com/111515188/204300946-08d4eb1f-b7e6-4019-bad6-6fb607581cbe.png)

But anyway, this shall be a problem of our future selves...

**Comment by Moult** [comment] 2022-11-28 22:07
I can try to help provide some clarity here:

Identifier | Version
--- | ---
IFC2X3 | 2.3.0.1
IFC4 | 4.0.2.1
IFC4X3 | No version confirmed yet, pending ISO certification

**Comment by andy-wrks** [comment] 2022-11-29 09:09
Ah cool, so it will get its own header identifier IFC4X3 once it's released? That's great and will make it possible to deal with the non backward-compatibility with IFC4.

**Comment by beachtom** [comment] 2022-11-29 09:31
So currently we use IFC2X3 and IFC4 in this repo. So this is all good. At some point we need to add IFC4X3 - but that can be done later

**Comment by Moult** [comment] 2022-11-29 09:46
> so it will get its own header identifier IFC4X3 once it's released?

Yes.

**Closed** 2023-02-04 08:29 UTC
