### ISSUE TITLE
[Bug]: Site Geo localisation not read in Archicad/Solibri because of trailing points after integers 

### ISSUE THREAD

**Issue by jonathan-buildrz** [IFCjs/web-ifc#422] opened 2023-06-21 10:02 UTC
### What happened?

Given the following IfcSite line in an IFC file:
`#118=IFCSITE('00000000-0000-4000-8000-000000000001',#5,'Project site',$,$,#47,#117,$,.COMPLEX.,(48.,10.,20.,30.),(2.,40.,50.,60.),0.,$,$);`
If opened in Archicad or Solibri, the localisation of the site will not be read and will be at 0/0.
If i remove the trailing points after the values:
`#118=IFCSITE('00000000-0000-4000-8000-000000000001',#5,'Project site',$,$,#47,#117,$,.COMPLEX.,(48,10,20,30),(2,40,50,60),0.,$,$);`
Then the localisation is read correctly in both softwares.
 According to the IFC specification, the values in IfcCompoundPlaneAngleMeasure are supposed to be integer:
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcmeasureresource/lexical/ifccompoundplaneanglemeasure.htm
Despite my searches, I couldn't find a definitive source on whether or not the trailing point should be there, apart from this statement:

REAL Decimal numbers (e.g. 2.56).
The decimal point must be present even if a number declared as REAL evaluates
to a whole number equivalent to an integer (e.g. 2.0).
**INTEGER A whole number not containing a fraction or decimal element (e.g. 2)**

https://standards.buildingsmart.org/documents/Implementation/The_EXPRESS_Definition_Language_for_IFC_Development.pdf

Also, I see that those values are defined as integers and not IfcIntegers, so I have no idea on how this could be done in typescript...

Also note that because of issue #421, the localisation in the ifc site is already the product of a work around ; however, the IfcTimestamp in the IfcOwnerHistory exhibits the same problem and doesn't need a workaround (I hesitated to open the bug report on that instead but went for the problem that provoked a real world nuisance)

### Version

0.0.41

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment] 2023-06-30 08:39
Just to say I am working on this - the fix for this is a little tricky. The issue is we need a trailing . if the data item is a REAL and a whole number - but we should have no trailing if it is an Integer

**Comment by beachtom** [comment] 2023-07-11 20:31
This should now be fixed

**Closed by beachtom** 2023-07-11 20:31 UTC
Labels: bug
